export const SET_COUNTER = 'SET_COUNTER';
export const SET_TEMPERATURE_CELSIUS = 'SET_TEMPERATURE_CELSIUS';
export const SET_TEMPERATURE_FAHRENHEIT = 'SET_TEMPERATURE_FAHRENHEIT';
export const SET_FLIGHT_ONE_WAY = 'SET_FLIGHT_ONE_WAY';
export const SET_FLIGHT_RETURN = 'SET_FLIGHT_RETURN';